[
    {
        "jobTitle": "Pessoa Analista de Desenvolvimento Java Pleno",
        "companyId": "Magalu",
        "income": 3000,
        "negotiable": false,
        "typeOfJob": "CLT",
        "modality": "hibrido",
        "seniority": "Pleno",
        "active": true,
        "jobDesc": "Nossas soluções são desenvolvidas e constantemente atualizadas por profissionais que conhecem a rotina do setor financeiro. Tudo isso para tornar sua operação mais digital, melhorar performance, oferecer inovação no atendimento aos clientes e manter as exigências regulatórias 100% em dia. Junte-se a nós! Sobre a vaga: Estamos buscando profissionais apaixonados por desenvolvimento de software e que gostem de analisar performance, infra-infraestrutura e arquitetura. Esperamos que esse desenvolvedor esteja sempre instigado a aperfeiçoar sua base de código utilizando as melhores práticas e além disso busquem grandes aspirações em se tornar cada vez melhores no que fazem, e melhor que isso, que não apenas queiram, mas que estejam dispostos a se manter em constante estado de aprendizado, inspeção e adaptação."
    },
    {
        "jobTitle": "Analista de Desenvolvimento Java / Pleno",
        "companyId": "Magalu",
        "income": 4000,
        "negotiable": true,
        "typeOfJob": "CLT",
        "modality": "hibrido",
        "seniority": "Pleno",
        "active": true,
        "jobDesc": "Estamos à procura de um(a) profissional para atuar como Analista de Desenvolvimento Java. Seu objetivo é Desenvolver e implementar soluções de automação de processos, utilizando diversas linguagens de programação e tecnologias, visando redução de erros e custos, aprimoramento de qualidade dos serviços e processos e ganho de produtividade. Formação de nível superior ou pós graduação completa em TI; EConhecidmento na utilização da IDE Eclipse; design de interfaces de programação de aplicações (APIs); microserviços e containers; arquitetura de aplicações multi-tenancy; conhecimento em soluções para processamento Batch em Java. Experiência com java Web: JEE 6 ou superior, JSE, JSF, JPA; e Struts ; Javascript, ECMAScript, Ajax, JQuery, Angular JS 1.5 ou superior e Bootstrap, HTML 5, XML, CSS; aplicações Java SWING; ferramenta SonarQube; consultas a bancos de dados SQL; jUnit, Jmeter; Jenkins."
    },
    {
        "jobTitle": "Pessoa Desenvolvedora Backend Java e PL/SQL Pleno",
        "companyId": "fintechMagalu",
        "income": 6000,
        "negotiable": false,
        "typeOfJob": "PJ",
        "modality": "presencial",
        "seniority": "Pleno",
        "active": true,
        "jobDesc": "Com uma combinação de competências multidisciplinares, o nosso time está constantemente empenhado a entregar o melhor no domínio dos pagamentos instantâneos. Orgulhamo-nos de liderar soluções que revolucionam o cenário bancário digital e melhoram imensamente a experiência dos nossos clientes. Você trabalhará em projetos que atendem a um dos principais bancos globais do mundo. É uma chance de causar impacto onde é importante! Junte-se a uma equipe dinâmica que atua na vanguarda do mercado financeiro!"
    },
    {
        "jobTitle": "Desenvolvimento em Golang/React - Remoto",
        "companyId": "Americanas@gmail.com",
        "income": 5000,
        "negotiable": false,
        "typeOfJob": "CLT",
        "modality": "Remoto",
        "seniority": "Senior",
        "active": true,
        "jobDesc": "Formação superior em Engenharia Elétrica/Telecomunicações/Computação ou equivalentes; Experiência em desenvolvimento com linguagens de programação React e Go; Experiência em desenvolvimento de soluções com arquitetura de microsserviços em ambiente Kubernetes; Domínio de ferramentas de IaC (Terraform, Ansible, Helm); Domínio de ferramentas de desenvolvimento de software como Git, Bitbucket, Jenkins, JIRA, Artifactory;"
    },
    {
        "jobTitle": "Desenvolvedor de Software Java - Trabalho Remoto",
        "companyId": "Americanas@email.com",
        "income": 2000,
        "negotiable": true,
        "typeOfJob": "Presencial",
        "modality": "CLT",
        "seniority": "Junior",
        "active": true,
        "jobDesc": "Estamos buscando profissionais apaixonados por desenvolvimento de software e que tenham grandes aspirações em se tornar cada vez melhores no que fazem, e melhor que isso, que não apenas queiram, mas que estejam dispostos a se manter em constante estado de aprendizado, inspeção e adaptação. Buscar respostas interagindo com os demais em situações pertencentes ou não do seu dia-a-dia, desenvolvendo a multidisciplinaridade."
    },
    {
        "jobTitle": "Pessoa Desenvolvedora Fullstack III NodeJs/React",
        "companyId": "ti@email.com",
        "income": 4000,
        "negotiable": true,
        "typeOfJob": "Presencial",
        "modality": "PJ",
        "seniority": "Pleno",
        "active": true,
        "jobDesc": "responsabilidades: Participar da definição dos objetivos de suas entregas, bem como planejar e organizar suas próprias atividades para o atingimento dos objetivos. Ajudar seus colegas de equipe a superar obstáculos, resolver bloqueadores e concluir tarefas de trabalho de forma proativa. Participar das decisões na implementação dos produtos, compreendendo o domínio dos produtos onde participa, projetando soluções alinhadas com as definições de arquitetura existentes e auxiliando as outras pessoas desenvolvedoras em melhorias na arquitetura do produto."
    },
    {
        "jobTitle": "Full stack developer react e java",
        "companyId": "ti@email.com",
        "income": 6000,
        "negotiable": true,
        "typeOfJob": "presencial",
        "modality": "PJ",
        "seniority": "Senior",
        "active": true,
        "jobDesc": "E, para tirar de letra, você precisa:Sólidos conhecimentos em HTML, CSS e JavaScript;Experiência prévia com desenvolvimento em React, criando interfaces interativas e responsivas;Competência no desenvolvimento de APIs backend em Java;Habilidade na validação de requisições para assegurar a segurança ..."
    },
    {
        "jobTitle": "Desenvolvedor net junior",
        "companyId": "ti@email.com",
        "income": 2000,
        "negotiable": true,
        "typeOfJob": "remoto",
        "modality": "CLT",
        "seniority": "Junior",
        "active": true,
        "jobDesc": "A Sinqia, provedora da experiência mais desejada em tecnologia para o mercado financeiro no Brasil, está em busca de um(a) Business Analyst/PO para compor nosso time e nos ajudar a fazer o mercado financeiro pulsar! Nós somos a Sinqia. Bem-vindo ao agora!Acreditamos que a inovação tecnológica inspir..."
    },
    {
        "jobTitle": "Desenvolvedor(a) Backend Pleno (Voz) - Java e/ou Node.js",
        "companyId": "ti@email.com",
        "income": 5000,
        "negotiable": true,
        "typeOfJob": "Hibrido",
        "modality": "Freelancer",
        "seniority": "Pleno",
        "active": true,
        "jobDesc": "Trabalhar como parte de uma equipe desenvolvendo aplicativos e serviços usando métodos de desenvolvimento Agile; Contribuir para melhorias de equipe e organizacionais em processos e infraestrutura; Crie serviços de back-end de alta disponibilidade/alta escalabilidade em um ambiente em crescimento; Codifique, teste e opere serviços e aplicações Use efetivamente ferramentas e engenhosidade para identificar e corrigir defeitos antes que eles se tornem um problema;"
    },
    {
        "jobTitle": "Analista de Sustentação",
        "companyId": "ti@email.com",
        "income": 5000,
        "negotiable": true,
        "typeOfJob": "Remoto",
        "modality": "CLT",
        "seniority": "Pleno",
        "active": true,
        "jobDesc": "Responsável pela análise, investigação e resolução de requisições de serviço e incidentes originados no ambiente de produção pelos times operacionais ou pelas ferramentas de monitoramento, assim como criação de melhorias e evoluções dos processos e rotinas atuais; Absorver o conhecimento dos sistemas que estão subindo para a produção através da realização de transições junto aos times de desenvolvimento de modo a entender os cenários e estar apto a suportar as ferramentas e ambientes relacionados; Analisar e identificar se as soluções de monitoramento estão adequadas aos sistemas que estão sendo executados em produção, observando tanto os sistemas já existentes quanto os que estão sendo implementados no ambiente produtivo. "
    },
    {
        "jobTitle": "Desenvolvedor a back end pleno",
        "companyId": "magalu",
        "income": 6000,
        "negotiable": false,
        "typeOfJob": "Presencial",
        "modality": "CLT",
        "seniority": "Pleno",
        "active": true,
        "jobDesc": "Superior completo na área de TI;Experiência com desenvolvimento e consumo de API Rest na arquitetura Java;Experiência com Java (8 e 11), EJB, Spring Boot e JPA;Experiência com Testes Unitários (Junit/jupiter/mock) e análise de cobertura de testes;Experiência em modelagem de dados com estrutura"
    },
    {
        "jobTitle": "BACKEND SOFTWARE ENGINEER PLENO (HÍBRIDO - CAMPINAS/SP)",
        "companyId": "ti@email.com",
        "income": 8000,
        "negotiable": false,
        "typeOfJob": "Híbrido",
        "modality": "CLT",
        "seniority": "Pleno",
        "active": true,
        "jobDesc": "Desenvolver programas para computadores, mais complexos, verificando os projetos de arquivos e cadastro dos programas que compõe o sistema; Manter os padrões de projeto existentes e sugerir melhorias; Validar as novas funcionalidades das aplicações;"
    },
    {
        "jobTitle": "Pessoa Desenvolvedora Java Pleno",
        "companyId": "americanas@email.com",
        "income": 5000,
        "negotiable": false,
        "typeOfJob": "Presencial",
        "modality": "PJ",
        "seniority": "Pleno",
        "active": true,
        "jobDesc": "Estamos em busca de um desenvolvedor Java Pleno para se juntar à nossa equipe de tecnologia. O candidato ideal terá uma sólida experiência em desenvolvimento Java, especialmente em Spring Boot, APIs REST, e uma compreensão profunda de XML, JSON, SQL ANSI, Git, JWT e Swagger. O conhecimento em OpenAPI 3 e PLSQL será considerado um diferencial."
    },
    {
        "jobTitle": "Java/OpenAI",
        "companyId": "americanas@email.com",
        "income": 2000,
        "negotiable": false,
        "typeOfJob": "Remoto",
        "modality": "CLT",
        "seniority": "Júnior",
        "active": true,
        "jobDesc": "We're looking to hire a Java/OpenAI Developer to join our team. You'll work with our incredible clients in one of two ways: Team Augmentation: You will integrate yourself directly into our client's team and work alongside their existing designers and engineers on a daily basis. Design & Build: You will work on a FullStack product team to build and deliver a product to our clients."
    },
    {
        "jobTitle": "Java/OpenAI",
        "companyId": "Yupi@email.com",
        "income": 2600,
        "negotiable": false,
        "typeOfJob": "Remoto",
        "modality": "CLT",
        "seniority": "Júnior",
        "active": true,
        "jobDesc": "We're looking to hire a Java/OpenAI Developer to join our team. You'll work with our incredible clients in one of two ways: Team Augmentation: You will integrate yourself directly into our client's team and work alongside their existing designers and engineers on a daily basis. Design & Build: You will work on a FullStack product team to build and deliver a product to our clients."
    },
    {
        "jobTitle": "Desenvolvedor Back-end Pl",
        "companyId": "Yupi@email.com",
        "income": 2000,
        "negotiable": false,
        "typeOfJob": "Presencial",
        "modality": "CLT",
        "seniority": "Júnior",
        "active": true,
        "jobDesc": " Escrever consistentemente código pronto para produção que é facilmente testável, facilmente entendido por outros desenvolvedores e que leva em conta os casos extremos e os erros;Entender quando é apropriado deixar comentários, mas tende para o código auto documentado; Compreende a pirâmide de testes e escreve testes de unidade, bem como testes de nível superior de acordo com ela. Sempre escreve testes para lidar com casos de borda e erros esperados normalmente, bem como caminhos felizes;Proficiente no uso de depuração sistemática para diagnosticar todos os problemas localizados em um único serviço. Usa depuração sistemática para diagnosticar problemas entre serviços, às vezes com a ajuda de engenheiros mais experientes."
    },
    {
        "jobTitle": "Desenvolvedor Back-end Pl",
        "companyId": "Yupi@email.com",
        "income": 2000,
        "negotiable": false,
        "typeOfJob": "Presencial",
        "modality": "CLT",
        "seniority": "Júnior",
        "active": true,
        "jobDesc": " Escrever consistentemente código pronto para produção que é facilmente testável, facilmente entendido por outros desenvolvedores e que leva em conta os casos extremos e os erros;Entender quando é apropriado deixar comentários, mas tende para o código auto documentado; Compreende a pirâmide de testes e escreve testes de unidade, bem como testes de nível superior de acordo com ela. Sempre escreve testes para lidar com casos de borda e erros esperados normalmente, bem como caminhos felizes;Proficiente no uso de depuração sistemática para diagnosticar todos os problemas localizados em um único serviço. Usa depuração sistemática para diagnosticar problemas entre serviços, às vezes com a ajuda de engenheiros mais experientes."
    },
    {
        "jobTitle": "Desenvolvedor BackEnd - Remoto",
        "companyId": "Yupi@email.com",
        "income": 6000,
        "negotiable": false,
        "typeOfJob": "Remoto",
        "modality": "CLT",
        "seniority": "Pleno",
        "active": true,
        "jobDesc": " Alinhamentos com as equipes para discussão de progressos e atualizações para as áreas clientes, metas a serem alcançadas e quais tarefas devem ser realizadas durante o dia. Atuar no desenvolvimento de softwares e soluções relacionadas, sendo parte mais ativa de suas atividades do dia a dia. Isso pode envolver a criação de novos recursos, a resolução de problemas, a escrita de código, o desenvolvimento de APIs, a implementação de designs de interface de usuários entre outros olhares para todo o organismo."
    },
    {
        "jobTitle": "DESENVOLVEDOR(A) BACKEND PLENO - JAVA EE",
        "companyId": "Yupi@email.com",
        "income": 5500,
        "negotiable": true,
        "typeOfJob": "Remoto",
        "modality": "PJ",
        "seniority": "Pleno",
        "active": true,
        "jobDesc": "Somos uma empresa jovem que busca atendimento de excelência para seus clientes, respeitando cada parceiro de negócio, seja um profissional do time, fornecedor ou cliente. Inconformados com um mercado que preza por volume, buscamos padrões de excelência para conectar pessoas e sistemas e promover uma jornada digital incrível!"
    },
    {
        "jobTitle": "Desenvolvedor Java Júnior - Home Office",
        "companyId": "Yupi@email.com",
        "income": 5500,
        "negotiable": false,
        "typeOfJob": "Remoto",
        "modality": "PJ",
        "seniority": "Pleno",
        "active": true,
        "jobDesc": "Somos uma empresa jovem que busca atendimento de excelência para seus clientes, respeitando cada parceiro de negócio, seja um profissional do time, fornecedor ou cliente. Inconformados com um mercado que preza por volume, buscamos padrões de excelência para conectar pessoas e sistemas e promover uma jornada digital incrível!"
    },
    {
        "jobTitle": "Desenvolvedor(a) Java Pleno",
        "companyId": "Yupi@email.com",
        "income": 4000,
        "negotiable": true,
        "typeOfJob": "Presencial",
        "modality": "CLT",
        "seniority": "Pleno",
        "active": true,
        "jobDesc": "Nosso(a) Desenvolvedor(a) Java estará em contato com uma equipe multidisciplinar e atuará em diversos projetos internos e de clientes. Além disso, será responsável por administrar e suportar sistemas de missão crítica em cloud."
    },
    {
        "jobTitle": "Java Software Engineer",
        "companyId": "Yupi@email.com",
        "income": 7000,
        "negotiable": true,
        "typeOfJob": "Remoto",
        "modality": "CLT",
        "seniority": "Sênior",
        "active": true,
        "jobDesc": "We are looking for a software engineer to join the Live Inventory and Custom Integrations team to support and evolve the design, implementation, and operational support of systems that span the business side and engineering departments."
    },
    {
        "jobTitle": "Pessoa Desenvolvedora com cloud AWS and Java8+",
        "companyId": "Yupi@email.com",
        "income": 9000,
        "negotiable": true,
        "typeOfJob": "Remoto",
        "modality": "PJ",
        "seniority": "Sênior",
        "active": true,
        "jobDesc": "Você fará parte do desenvolvimento dos produtos mais inovadores do mercado, contribuindo para a criação de software de alto desempenho. Isso envolverá participar de discussões sobre a arquitetura do sistema e identificar as melhores abordagens para resolver desafios específicos. No seu dia a dia, além de desenvolver a plataforma, você realizará revisões de código entre colegas, contribuindo para a qualidade do nosso código entregue. Venha fazer a diferença com a gente!"
    },
    {
        "jobTitle": "ANALISTA DESENVOLVEDOR JAVA JR",
        "companyId": "Yupi@email.com",
        "income": 3000,
        "negotiable": true,
        "typeOfJob": "Remoto",
        "modality": "CLT",
        "seniority": "Júnior",
        "active": true,
        "jobDesc": "Colaboração e comprometimento fazem parte do nosso dia-a-dia, quando desenvolvemos novas funcionalidades, construindo um produto robusto e escalável. Fazendo parte de nossa equipe, seu trabalho irá impactar em milhares de usuários que utilizam nossas soluções diariamente."
    },
    {
        "jobTitle": "Engenheiro de Software Pl - Java",
        "companyId": "Yupi@email.com",
        "income": 6000,
        "negotiable": false,
        "typeOfJob": "Presencial",
        "modality": "PJ",
        "seniority": "Pleno",
        "active": true,
        "jobDesc": "Esse squad possui atuação global, ou seja, temos membros do time em diversos lugares do globo, principalmente no Brasil, Canadá, Estados Unidos e Índia, portanto, trabalhar com diferentes fuso-horários também faz parte do nosso dia a dia. Somos um dos principais squads fornecedor do produto para nossos clientes (internos e externos) portanto qualidade no desenvolvimento e entrega é um tema indiscutível para nós. Interação com os demais times internos também é esperado, como: time de QA (quality assurance), time de documentação, time de produto e demais times de engenharia."
    },
    {
        "jobTitle": "Desenvolvedor Java",
        "companyId": "Yupi@email.com",
        "income": 9000,
        "negotiable": false,
        "typeOfJob": "Híbrido",
        "modality": "CLT",
        "seniority": "Sênior",
        "active": true,
        "jobDesc": "Responsabilidades e atribuições: Desenvolver aplicações utilizando a linguagem Java. Participar do ciclo completo de desenvolvimento, desde o design até a implantação. Trabalhar em conjunto com uma equipe ágil, seguindo práticas como testes automatizados e integração contínua. Contribuir para o aprimoramento de soluções existentes e auxiliar na resolução de problemas."
    },
    {
        "jobTitle": "Desenvolvedor Backend Java Pleno",
        "companyId": "Yupi@email.com",
        "income": 6666,
        "negotiable": false,
        "typeOfJob": "Híbrido",
        "modality": "PJ",
        "seniority": "Pleno",
        "active": true,
        "jobDesc": "Requisitos: Experiência com Desenvolvimento de Aplicações para o mercado Financeiro. Frameworks de Frontend Web Modernos (AngularJS, ReactJS, EmberJS). Experiência com Testes de Integração e Aceitação. Conhecimentos em Spring Cloud e Nefflix OSS são um grande diferencial. Conhecimentos em programação funcional e imutabilidade."
    },
    {
        "jobTitle": "Pessoa Desenvolvedora Backend Java",
        "companyId": "Yupi@email.com",
        "income": 3000,
        "negotiable": false,
        "typeOfJob": "Presencial",
        "modality": "PJ",
        "seniority": "Júnior",
        "active": true,
        "jobDesc": "Linguagem JavaConhecimento no Framework Spring e Spring Boot. Conhecimento em GIT. Conhecimento em banco de dados Oracle"
    },
    {
        "jobTitle": "Developer Backend Sr (Java)",
        "companyId": "Yupi@email.com",
        "income": 9600,
        "negotiable": true,
        "typeOfJob": "Remoto",
        "modality": "CLT",
        "seniority": "Sênior",
        "active": true,
        "jobDesc": "Na nossa cultura, valorizamos colaboração, autonomia e mentalidade empreendedora. Aprendemos muito com pessoas de diferentes lugares e áreas da empresa e oferecemos liberdade para cada Rethinker contribuir com o que tem de melhor para a nossa comunidade. Por aqui, não fazemos distinção. Todas as pessoas que se identificam com nossa cultura e que cumprem o esperado nessa vaga são convidadas a se candidatar!"
    },
    {
        "jobTitle": "Jr. Software Engineer",
        "companyId": "Yupi@email.com",
        "income": 3500,
        "negotiable": true,
        "typeOfJob": "Presencial",
        "modality": "CLT",
        "seniority": "Júnior",
        "active": true,
        "jobDesc": "Somos um software company 100% brasileira com foco no mercado de Incorporação. Oferecemos a plataforma mais completa do mercado para incorporadoras, com software, performance digital e consultoria em um único lugar."
    }
]
